### ISSUE TITLE
没办法执行

### ISSUE THREAD

**Issue by Pa55w0rd** [NHPT/xray1.9.0-Preview-Cracked#1]
[root@VM-24-15-centos xray1.9.0-Preview-Cracked]# ./xray_linux_amd64 ws -h
./xray_linux_amd64: line 1: version: command not found
./xray_linux_amd64: line 2: oid: command not found
size: '31311596': No such file

**Comment by NHPT** [comment]
换操作系统吧，ubuntu和debian应该没问题的，我在kali下没问题

**Comment by sn00pyd0g3** [comment]
git lfs clone 。。。

**Comment by houdinicc** [comment]
┌──(root㉿kali)-[/home/kali/xray]
└─# ./xray_linux_amd64 -h
illegal base64 data at input byte 0
